load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SwiftSoup",
    srcs = glob(["Sources/**/*.swift"]),
    module_name = "SwiftSoup",
    visibility = ["//visibility:public"],
)
