objc_library(
    name = "HTTPServer",
    srcs = glob(["Sources/**/*.mm"]),
    hdrs = glob(["Sources/**/*.h"]),
    module_name = "HTTPServer",
    visibility = ["//visibility:public"],
    deps = ["@cpp-httplib//:cpp-httplib"],
)
