load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Localization",
    srcs = glob(["Sources/**/*.swift"]),
    module_name = "Localization",
    visibility = ["//visibility:public"],
    deps = [],
)
