package(default_visibility = ["//visibility:public"])

cc_library(
    name = "libuv",
    srcs = [
        "src/fs-poll.c",
        "src/idna.c",
        "src/inet.c",
        "src/random.c",
        "src/strscpy.c",
        "src/strtok.c",
        "src/thread-common.c",
        "src/threadpool.c",
        "src/timer.c",
        "src/uv-common.c",
        "src/uv-data-getter-setters.c",
        "src/version.c",
        "src/unix/async.c",
        "src/unix/bsd-ifaddrs.c",
        "src/unix/core.c",
        "src/unix/darwin-proctitle.c",
        "src/unix/darwin.c",
        "src/unix/dl.c",
        "src/unix/fs.c",
        "src/unix/fsevents.c",
        "src/unix/getaddrinfo.c",
        "src/unix/getnameinfo.c",
        "src/unix/kqueue.c",
        "src/unix/loop-watcher.c",
        "src/unix/loop.c",
        "src/unix/pipe.c",
        "src/unix/poll.c",
        "src/unix/process.c",
        "src/unix/proctitle.c",
        "src/unix/random-devurandom.c",
        "src/unix/random-getentropy.c",
        "src/unix/signal.c",
        "src/unix/stream.c",
        "src/unix/tcp.c",
        "src/unix/thread.c",
        "src/unix/tty.c",
        "src/unix/udp.c",
    ],
    hdrs = glob([
        "include/**/*.h",
        "src/*.h",
        "src/unix/*.h",
    ]),
    copts = [
        "-fno-strict-aliasing",
        "-Wno-unused-parameter",
    ],
    defines = [
        "_DARWIN_UNLIMITED_SELECT=1",
        "_DARWIN_USE_64_BIT_INODE=1",
        "_FILE_OFFSET_BITS=64",
        "_LARGEFILE_SOURCE",
    ],
    includes = [
        "include",
        "src",
    ],
    linkstatic = True,
)
