load("@build_bazel_rules_swift//swift:swift.bzl", "swift_binary")

swift_binary(
    name = "Packager",
    srcs = glob(["Packager/*.swift"]),
    visibility = ["//visibility:public"],
    deps = [
    ],
)
