// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public enum zzz_DflatGen_TextType: Int8, Enum, Verifiable {
  public typealias T = Int8
  public static var byteSize: Int { return MemoryLayout<Int8>.size }
  public var value: Int8 { return self.rawValue }
  case positivetext = 0
  case negativetext = 1

  public static var max: zzz_DflatGen_TextType { return .negativetext }
  public static var min: zzz_DflatGen_TextType { return .positivetext }
}

public struct zzz_DflatGen_TextRange: NativeStruct, Verifiable, FlatbuffersInitializable {

  static func validateVersion() { FlatBuffersVersion_22_9_29() }

  private var _location: Int32
  private var _length: Int32

  public init(_ bb: ByteBuffer, o: Int32) {
    let _accessor = Struct(bb: bb, position: o)
    _location = _accessor.readBuffer(of: Int32.self, at: 0)
    _length = _accessor.readBuffer(of: Int32.self, at: 4)
  }

  public init(location: Int32, length: Int32) {
    _location = location
    _length = length
  }

  public init() {
    _location = 0
    _length = 0
  }

  public var location: Int32 { _location }
  public var length: Int32 { _length }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws
  where T: Verifiable {
    try verifier.inBuffer(position: position, of: zzz_DflatGen_TextRange.self)
  }
}

public struct zzz_DflatGen_TextRange_Mutable: FlatBufferObject {

  static func validateVersion() { FlatBuffersVersion_22_9_29() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Struct

  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Struct(bb: bb, position: o) }

  public var location: Int32 { return _accessor.readBuffer(of: Int32.self, at: 0) }
  public var length: Int32 { return _accessor.readBuffer(of: Int32.self, at: 4) }
}

public struct zzz_DflatGen_TextModification: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_22_9_29() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static func getRootAsTextModification(bb: ByteBuffer) -> zzz_DflatGen_TextModification {
    return zzz_DflatGen_TextModification(
      Table(
        bb: bb, position: Int32(bb.read(def: UOffset.self, position: bb.reader)) + Int32(bb.reader))
    )
  }

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case type = 4
    case range = 6
    case text = 8
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var type: zzz_DflatGen_TextType {
    let o = _accessor.offset(VTOFFSET.type.v)
    return o == 0
      ? .positivetext
      : zzz_DflatGen_TextType(rawValue: _accessor.readBuffer(of: Int8.self, at: o)) ?? .positivetext
  }
  public var range: zzz_DflatGen_TextRange? {
    let o = _accessor.offset(VTOFFSET.range.v)
    return o == 0 ? nil : _accessor.readBuffer(of: zzz_DflatGen_TextRange.self, at: o)
  }
  public var mutableRange: zzz_DflatGen_TextRange_Mutable? {
    let o = _accessor.offset(VTOFFSET.range.v)
    return o == 0 ? nil : zzz_DflatGen_TextRange_Mutable(_accessor.bb, o: o + _accessor.postion)
  }
  public var text: String? {
    let o = _accessor.offset(VTOFFSET.text.v)
    return o == 0 ? nil : _accessor.string(at: o)
  }
  public var textSegmentArray: [UInt8]? { return _accessor.getVector(at: VTOFFSET.text.v) }
  public static func startTextModification(_ fbb: inout FlatBufferBuilder) -> UOffset {
    fbb.startTable(with: 3)
  }
  public static func add(type: zzz_DflatGen_TextType, _ fbb: inout FlatBufferBuilder) {
    fbb.add(element: type.rawValue, def: 0, at: VTOFFSET.type.p)
  }
  public static func add(range: zzz_DflatGen_TextRange?, _ fbb: inout FlatBufferBuilder) {
    guard let range = range else { return }
    fbb.create(struct: range, position: VTOFFSET.range.p)
  }
  public static func add(text: Offset, _ fbb: inout FlatBufferBuilder) {
    fbb.add(offset: text, at: VTOFFSET.text.p)
  }
  public static func endTextModification(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset {
    let end = Offset(offset: fbb.endTable(at: start))
    return end
  }
  public static func createTextModification(
    _ fbb: inout FlatBufferBuilder,
    type: zzz_DflatGen_TextType = .positivetext,
    range: zzz_DflatGen_TextRange? = nil,
    textOffset text: Offset = Offset()
  ) -> Offset {
    let __start = zzz_DflatGen_TextModification.startTextModification(&fbb)
    zzz_DflatGen_TextModification.add(type: type, &fbb)
    zzz_DflatGen_TextModification.add(range: range, &fbb)
    zzz_DflatGen_TextModification.add(text: text, &fbb)
    return zzz_DflatGen_TextModification.endTextModification(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws
  where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(
      field: VTOFFSET.type.p, fieldName: "type", required: false, type: zzz_DflatGen_TextType.self)
    try _v.visit(
      field: VTOFFSET.range.p, fieldName: "range", required: false,
      type: zzz_DflatGen_TextRange.self)
    try _v.visit(
      field: VTOFFSET.text.p, fieldName: "text", required: false, type: ForwardOffset<String>.self)
    _v.finish()
  }
}

public struct zzz_DflatGen_TextHistoryNode: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_22_9_29() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static func getRootAsTextHistoryNode(bb: ByteBuffer) -> zzz_DflatGen_TextHistoryNode {
    return zzz_DflatGen_TextHistoryNode(
      Table(
        bb: bb, position: Int32(bb.read(def: UOffset.self, position: bb.reader)) + Int32(bb.reader))
    )
  }

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case lineage = 4
    case logicalTime = 6
    case startEdits = 8
    case startPositiveText = 10
    case startNegativeText = 12
    case modifications = 14
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var lineage: Int64 {
    let o = _accessor.offset(VTOFFSET.lineage.v)
    return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o)
  }
  public var logicalTime: Int64 {
    let o = _accessor.offset(VTOFFSET.logicalTime.v)
    return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o)
  }
  public var startEdits: Int64 {
    let o = _accessor.offset(VTOFFSET.startEdits.v)
    return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o)
  }
  public var startPositiveText: String? {
    let o = _accessor.offset(VTOFFSET.startPositiveText.v)
    return o == 0 ? nil : _accessor.string(at: o)
  }
  public var startPositiveTextSegmentArray: [UInt8]? {
    return _accessor.getVector(at: VTOFFSET.startPositiveText.v)
  }
  public var startNegativeText: String? {
    let o = _accessor.offset(VTOFFSET.startNegativeText.v)
    return o == 0 ? nil : _accessor.string(at: o)
  }
  public var startNegativeTextSegmentArray: [UInt8]? {
    return _accessor.getVector(at: VTOFFSET.startNegativeText.v)
  }
  public var hasModifications: Bool {
    let o = _accessor.offset(VTOFFSET.modifications.v)
    return o == 0 ? false : true
  }
  public var modificationsCount: Int32 {
    let o = _accessor.offset(VTOFFSET.modifications.v)
    return o == 0 ? 0 : _accessor.vector(count: o)
  }
  public func modifications(at index: Int32) -> zzz_DflatGen_TextModification? {
    let o = _accessor.offset(VTOFFSET.modifications.v)
    return o == 0
      ? nil
      : zzz_DflatGen_TextModification(
        _accessor.bb, o: _accessor.indirect(_accessor.vector(at: o) + index * 4))
  }
  public static func startTextHistoryNode(_ fbb: inout FlatBufferBuilder) -> UOffset {
    fbb.startTable(with: 6)
  }
  public static func add(lineage: Int64, _ fbb: inout FlatBufferBuilder) {
    fbb.add(element: lineage, def: 0, at: VTOFFSET.lineage.p)
  }
  public static func add(logicalTime: Int64, _ fbb: inout FlatBufferBuilder) {
    fbb.add(element: logicalTime, def: 0, at: VTOFFSET.logicalTime.p)
  }
  public static func add(startEdits: Int64, _ fbb: inout FlatBufferBuilder) {
    fbb.add(element: startEdits, def: 0, at: VTOFFSET.startEdits.p)
  }
  public static func add(startPositiveText: Offset, _ fbb: inout FlatBufferBuilder) {
    fbb.add(offset: startPositiveText, at: VTOFFSET.startPositiveText.p)
  }
  public static func add(startNegativeText: Offset, _ fbb: inout FlatBufferBuilder) {
    fbb.add(offset: startNegativeText, at: VTOFFSET.startNegativeText.p)
  }
  public static func addVectorOf(modifications: Offset, _ fbb: inout FlatBufferBuilder) {
    fbb.add(offset: modifications, at: VTOFFSET.modifications.p)
  }
  public static func endTextHistoryNode(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset {
    let end = Offset(offset: fbb.endTable(at: start))
    return end
  }
  public static func createTextHistoryNode(
    _ fbb: inout FlatBufferBuilder,
    lineage: Int64 = 0,
    logicalTime: Int64 = 0,
    startEdits: Int64 = 0,
    startPositiveTextOffset startPositiveText: Offset = Offset(),
    startNegativeTextOffset startNegativeText: Offset = Offset(),
    modificationsVectorOffset modifications: Offset = Offset()
  ) -> Offset {
    let __start = zzz_DflatGen_TextHistoryNode.startTextHistoryNode(&fbb)
    zzz_DflatGen_TextHistoryNode.add(lineage: lineage, &fbb)
    zzz_DflatGen_TextHistoryNode.add(logicalTime: logicalTime, &fbb)
    zzz_DflatGen_TextHistoryNode.add(startEdits: startEdits, &fbb)
    zzz_DflatGen_TextHistoryNode.add(startPositiveText: startPositiveText, &fbb)
    zzz_DflatGen_TextHistoryNode.add(startNegativeText: startNegativeText, &fbb)
    zzz_DflatGen_TextHistoryNode.addVectorOf(modifications: modifications, &fbb)
    return zzz_DflatGen_TextHistoryNode.endTextHistoryNode(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws
  where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.lineage.p, fieldName: "lineage", required: false, type: Int64.self)
    try _v.visit(
      field: VTOFFSET.logicalTime.p, fieldName: "logicalTime", required: false, type: Int64.self)
    try _v.visit(
      field: VTOFFSET.startEdits.p, fieldName: "startEdits", required: false, type: Int64.self)
    try _v.visit(
      field: VTOFFSET.startPositiveText.p, fieldName: "startPositiveText", required: false,
      type: ForwardOffset<String>.self)
    try _v.visit(
      field: VTOFFSET.startNegativeText.p, fieldName: "startNegativeText", required: false,
      type: ForwardOffset<String>.self)
    try _v.visit(
      field: VTOFFSET.modifications.p, fieldName: "modifications", required: false,
      type: ForwardOffset<
        Vector<ForwardOffset<zzz_DflatGen_TextModification>, zzz_DflatGen_TextModification>
      >.self)
    _v.finish()
  }
}
