// automatically generated by the FlatBuffers compiler, do not modify
// swiftlint:disable all
// swiftformat:disable all

import FlatBuffers

public struct zzz_DflatGen_TextLineageNode: FlatBufferObject, Verifiable {

  static func validateVersion() { FlatBuffersVersion_22_9_29() }
  public var __buffer: ByteBuffer! { return _accessor.bb }
  private var _accessor: Table

  public static func getRootAsTextLineageNode(bb: ByteBuffer) -> zzz_DflatGen_TextLineageNode {
    return zzz_DflatGen_TextLineageNode(
      Table(
        bb: bb, position: Int32(bb.read(def: UOffset.self, position: bb.reader)) + Int32(bb.reader))
    )
  }

  private init(_ t: Table) { _accessor = t }
  public init(_ bb: ByteBuffer, o: Int32) { _accessor = Table(bb: bb, position: o) }

  private enum VTOFFSET: VOffset {
    case lineage = 4
    case pointTo = 6
    var v: Int32 { Int32(self.rawValue) }
    var p: VOffset { self.rawValue }
  }

  public var lineage: Int64 {
    let o = _accessor.offset(VTOFFSET.lineage.v)
    return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o)
  }
  public var pointTo: Int64 {
    let o = _accessor.offset(VTOFFSET.pointTo.v)
    return o == 0 ? 0 : _accessor.readBuffer(of: Int64.self, at: o)
  }
  public static func startTextLineageNode(_ fbb: inout FlatBufferBuilder) -> UOffset {
    fbb.startTable(with: 2)
  }
  public static func add(lineage: Int64, _ fbb: inout FlatBufferBuilder) {
    fbb.add(element: lineage, def: 0, at: VTOFFSET.lineage.p)
  }
  public static func add(pointTo: Int64, _ fbb: inout FlatBufferBuilder) {
    fbb.add(element: pointTo, def: 0, at: VTOFFSET.pointTo.p)
  }
  public static func endTextLineageNode(_ fbb: inout FlatBufferBuilder, start: UOffset) -> Offset {
    let end = Offset(offset: fbb.endTable(at: start))
    return end
  }
  public static func createTextLineageNode(
    _ fbb: inout FlatBufferBuilder,
    lineage: Int64 = 0,
    pointTo: Int64 = 0
  ) -> Offset {
    let __start = zzz_DflatGen_TextLineageNode.startTextLineageNode(&fbb)
    zzz_DflatGen_TextLineageNode.add(lineage: lineage, &fbb)
    zzz_DflatGen_TextLineageNode.add(pointTo: pointTo, &fbb)
    return zzz_DflatGen_TextLineageNode.endTextLineageNode(&fbb, start: __start)
  }

  public static func verify<T>(_ verifier: inout Verifier, at position: Int, of type: T.Type) throws
  where T: Verifiable {
    var _v = try verifier.visitTable(at: position)
    try _v.visit(field: VTOFFSET.lineage.p, fieldName: "lineage", required: false, type: Int64.self)
    try _v.visit(field: VTOFFSET.pointTo.p, fieldName: "pointTo", required: false, type: Int64.self)
    _v.finish()
  }
}
